/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IndexPage {}
  interface PocValue {
    'valuer': any;
  }
}

declare global {


  interface HTMLIndexPageElement extends Components.IndexPage, HTMLStencilElement {}
  const HTMLIndexPageElement: {
    prototype: HTMLIndexPageElement;
    new (): HTMLIndexPageElement;
  };

  interface HTMLPocValueElement extends Components.PocValue, HTMLStencilElement {}
  const HTMLPocValueElement: {
    prototype: HTMLPocValueElement;
    new (): HTMLPocValueElement;
  };
  interface HTMLElementTagNameMap {
    'index-page': HTMLIndexPageElement;
    'poc-value': HTMLPocValueElement;
  }
}

declare namespace LocalJSX {
  interface IndexPage {}
  interface PocValue {
    'valuer'?: any;
  }

  interface IntrinsicElements {
    'index-page': IndexPage;
    'poc-value': PocValue;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'index-page': LocalJSX.IndexPage & JSXBase.HTMLAttributes<HTMLIndexPageElement>;
      'poc-value': LocalJSX.PocValue & JSXBase.HTMLAttributes<HTMLPocValueElement>;
    }
  }
}


