/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IndexPage {}
}

declare global {


  interface HTMLIndexPageElement extends Components.IndexPage, HTMLStencilElement {}
  var HTMLIndexPageElement: {
    prototype: HTMLIndexPageElement;
    new (): HTMLIndexPageElement;
  };
  interface HTMLElementTagNameMap {
    'index-page': HTMLIndexPageElement;
  }
}

declare namespace LocalJSX {
  interface IndexPage {}

  interface IntrinsicElements {
    'index-page': IndexPage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'index-page': LocalJSX.IndexPage & JSXBase.HTMLAttributes<HTMLIndexPageElement>;
    }
  }
}


